Makefile

Add an optional variable to the Makefile to allow passing custom flags to the pytest command.

Accept configurable pytest args from env var

---

src/sparsify/utils/system.py

Addresses issue in #121 
When onnxruntime is not installed, the `available_ml_engines()` function would try to access a method on `None`.

Fixing available_ml_engines crash

---

src/sparsify/package/cli.py
src/sparsify/package/main.py
tests/sparsify/package/test_cli.py

The following PR has 3 small changes:
1) Improve output from `sparsify.package`, the output now also displays model metrics
2) Update `--optimizing_metric` arg to take in a comma separated value for metrics over `click's multiple option`
3) Update usage instructions accordingly
Note: for local testing kindly set `SPARSIFY_BACKEND_URL` to the url of local backend server
example: let's say the server runs on `http://0.0.0.0:8000` then  `export SPARSIFY_BACKEND_URL=http://0.0.0.0:8000`
Depends on sparsify backend diff: https://github.com/neuralmagic/model-api-service/pull/1
Tests: Manual testing + Automated test
For manual test,
- Export `SPARSIFY_BACKEND_URL=...`
- Spin up the server from `model-api-service` using `bash bin/run-local`
- Use sparsify.package based on help, if the help …

`sparsify.package` updates

---

docker/Dockerfile
src/sparsify/package/cli.py
tests/sparsify/package/test_cli.py

The following PR accomplishes the following:
- Adds a `Dockerfile` to build and install `deepsparse.server`
- Downloads deployment directory
- Update instructions for user
- Update tests
The new user instructions allow the user to input just one command inside sparsify/docker directory to install all dependencies and deploy a deepsparse server with the most appropriate model from `sparsify.package`
Example User instructions look like the following:
downloading...: 100%|████████████████████████| 104M/104M [00:08<00:00, 12.5MB/s]
downloading...: 100%|████████████████████████| 455k/455k [00:00<00:00, 3.18MB/s]
downloading...: 100%|███████████████████████████| 718/718 [00:00<00:00, 493kB/s]
downloading...: 100%|███████████████████████████| 384/384 [00:00<00:00, 275kB/s]
Relevant Stub: …

Update the user output for `sparsify.package`

---

src/sparsify/create/README.MD
src/sparsify/create/__init__.py
src/sparsify/create/api.py
src/sparsify/create/schemas.py
tests/sparsify/create/__init__.py
tests/sparsify/create/test_api.py

`sparsify.create` API pathway that creates a recipe and automatically enables sparsification aware training via sparseml.
Documentation of current capabilities included in the `README.MD`.
follow ups: Loggers
**test_plan:**
Simple E2E test included using mobilenet and simulated training steps

[Create] alpha implementation

---

setup.py
src/sparsify/__init__.py
src/sparsify/auto/utils/nm_api.py
src/sparsify/login.py
src/sparsify/one_shot/api.py
src/sparsify/utils/exceptions.py
src/sparsify/utils/helpers.py

This PR adds a `sparsify.login` utility to authenticate users with a valid `api_key` from sparsify cloud;
After authentication, the utility saves credentials at `~/.config/neuralmagic/credentials.json` and goes onto
install proprietary `sparsifyml` dependency from Neural Magic PyPi Server
As of now, we only have `sparsifyml_nightly` pushed up; this should change to `sparsifyml` once the package is updated.
Usage:
```bash
Usage: sparsify.login [OPTIONS]
sparsify.login utility to log into sparsify locally.
Options:
--api-key TEXT  API key copied from your account.  [required]
--version       Show the version and exit.  [default: False]
--help          Show this message and exit.  [default: False]
```
example:
```bash
sparsify.login --api-key [API-KEY]
```
Note: Kindly reach out for a dummy …

[Add] `sparsify.login` CLI and function

---

setup.py

this avoids installing additional third party dependencies on the install of sparsifyml, instead it will just be pulling down the sparsifyml code only after credentials are verified

add sparsifyml dependencies to sparsify install

---

src/sparsify/cli/run.py

recipe_args is already a supported CLI input that is a no-op, since this will be supported in the one shot backend, this PR propagates the value

[sparsify.run one-shot] CLI propagation of recipe_args

---

src/sparsify/cli/opts.py
src/sparsify/cli/run.py
src/sparsify/one_shot/api.py

Remove hardware optimization targets as options for Sparsify One-Shot and Training-Aware. Instead, optimization will be based on an "optimization target" implemented in other PRs.

Remove hardware optimization options

---

setup.py
src/sparsify/__init__.py
src/sparsify/apply.py
src/sparsify/cli/run.py
src/sparsify/init.py

This PR represents the feature branch for `sparsify.apply` cli push
sparsify.apply is a CLI utility, used to run the specified experiments initialized using `sparsify.init`
```bash
sparsify.apply --help
Usage: sparsify.apply [OPTIONS]
sparsify.apply CLI utility to apply sparsify to a given experiment, or
initialize and run an experiment if not created yet.
Options:
--experiment-type [sparse-transfer|one-shot|training-aware]
The type of the experiment to run.
--use-case [document_classification|image_classification|information_retrieval|masked_language_modeling|multilabel_text_classification|object_detection|question_answering|segmentation|sentiment_analysis|text_classification|token_classification]
The task this model is for.
--project-id TEXT               Id of the project this run …
```

`sparsify.apply`

---

src/sparsify/login.py

This PR updates api-key to be a required argument for sparsify.login
```bash
sparsify.login --help
Usage: sparsify.login [OPTIONS] API_KEY
sparsify.login utility to log into sparsify locally.
sparsify.login [API_KEY]
API_KEY: The API key copied from your sparsify account
Options:
--version  Show the version and exit.  [default: False]
--help     Show this message and exit.  [default: False]
```
Error Message:
```bash
sparsify.login
Usage: sparsify.login [OPTIONS] API_KEY
Try 'sparsify.login --help' for help.
Error: Missing argument 'API_KEY'.
```
Valid Usage with debug: (api key hidden)
```bash
sparsify.login  ********************* --debug
INFO:sparsify.login:Logging into sparsify...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.neuralmagic.com:443 …
```

Make API KEY an argument for `sparsify.login`

---

tests/sparsify/auto/test_main.py

This PR removes a bunch of outdated tests for `sparsify.alpha`, which were failing and stopping code from being merged into `sparsify.alpha`
Test plan:
All tests should be green now

[BugFixes] Fix failing tests in `sparsify.alpha`

---

.github/ISSUE_TEMPLATE/bug_report.md
DEVELOPING.md
README.md
setup.py

This PR deprecated Python3.7  support as it reaches EOL in about 2 weeks
https://endoflife.date/python

Deprecate Py37

---

Makefile

currently fails as `ui` has been removed.
@rahul-tuli to cherry pick to `beta` branch as well

remove legacy UI cmds from `make build`

---

Makefile

[Cherry pick] remove legacy UI cmds from `make build` (#229)

---

src/sparsify/auto/scripts/__init__.py

Currently the wheel build process fails to include the `/scripts` directory due to a missing `__init__.py` file. This PR remedies that.

Fix incomplete wheel build

---

.github/workflows/test-check.yaml

Currently GHA installs `sparseml[yolov5]` for running auto tests, this can lead to an older install of sparsezoo/sparseml packages and cause errors in tests like the following:
https://github.com/neuralmagic/sparsify/actions/runs/5326675996/jobs/9649024641?pr=213
in this case sparsezoo-nightly~=1.6 was downgraded to `sparsezoo~=1.5` which does not have the relevant bugfixes.
Proposed PR fixes that by using sparseml-nightly for auto tests
After rebasing on this PR the tests pass: https://github.com/neuralmagic/sparsify/actions/runs/5335310317/jobs/9668344241?pr=213

Update GHA file for auto tests

---

src/sparsify/login.py

Before this PR authenticated sparsifyml installs always installed a nightly version. This PR adds support to target sparsifyml release package when installed sparsify is also a release version
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204876488998965

Add support to download non-nightly sparsifyml package

---

setup.py

see https://github.com/neuralmagic/deepsparse/pull/1104
testing and support for latest pydantic to be added in future release

pin pydantic to <2.0

---

.github/workflows/quality-check.yaml
.github/workflows/test-check.yaml

Pip 22.0 and 22.0.1 give AssertionError when trying to resolve dependencies; --upgrade pip in GHA is recommended before running tests
This PR also cleans up GHA files for sparsify
Issue on PyPa: https://github.com/pypa/pip/issues/10851

Clean GHA files post merge

---

src/sparsify/auto/tasks/runner.py

For this ticket - https://app.asana.com/0/1204777926187571/1204947833549381/f
We want to only enable DDP if cuda/gpus are available. Ticket relates to the way `WORLD_SIZE` is set by pytorch during cpu distributed training.

[BUG] Update `DDP_ENABLED` flag

---

setup.py
src/sparsify/check_environment/__init__.py
src/sparsify/check_environment/gpu_device.py
src/sparsify/check_environment/main.py
src/sparsify/check_environment/ort_health.py
src/sparsify/check_environment/pathway_checks.py
src/sparsify/cli/run.py

This PR adds environment checks that will help detect a broken sparsify environment before a run is fully launched. There are three pathways by which environment checks are launched:
- The CLI command `sparsify.check_environment` will run all health checks
- Running an experiment with `sparsify.run training-aware` or `sparsify.run sparse-transfer` will run health checks relevant to these two pathways
- Running an experiment with `sparsify.run one-shot` will run the health checks relevant to one-shot
Currently implemented health checks
GPU device check - this is a non-failing check, but it will raise a loud error
ORT health check - this is a failing check which will point the user to the ORT-GPU dependency matrix
**Test Plan**

Add environment checks

---

src/sparsify/auto/tasks/image_classification/args.py
src/sparsify/auto/tasks/transformers/args.py

This PR turns on QAT folding on by default, so that `sprasify.training_aware` and `sparsify.sparse_transfer` always return fully quantized graphs.
Note that YOLOv5 always does QAT folding by default.
**Test Plan**
Tested with integration tests yet to land - https://github.com/neuralmagic/sparsify/pull/217

Turn QAT folding on by default

---

src/sparsify/auto/tasks/transformers/runner.py

Ticket: https://app.asana.com/0/1204322589046915/1204958994867569/f
Currently, our transformer workflows expect public datasets for the `data` arg when running sparsify auto and all other data files should be passed in to kwargs. This PR checks if the `data` arg passed in is a directory and if it is, populates the kwargs for the user and sets the original `data` arg to None. 
Made a couple of assumptions:
-  The train, test and val data files in the `data` arg directory should have the subtrings `train`, `test` and `val` in the filenames
-  Only one train, test and val file is present with the appropriate substring in the name. If multiple are present, it will only use one.
- You will either provide a data directory or a publicly available dataset that we then download within sparseml
No …

Parse out the `data` arg for transformer workflows to populate train/test/validation kwargs

---

setup.py
src/sparsify/auto/tasks/transformers/runner.py

glue datasets in HF such as sst2 and qqp are actually stored under the glue dataset name with their task names as the desired dataset name. this PR adds a connivence in the auto pathways to nest any recognized glue datasets under the glue namespace
**testing:**
reproduced and fixed error for minimal reproducible command:
```
sparsify.run sparse-transfer --use-case text-classification --data qqp
```

[transformers] unwrap GLUE dataset alias for classification sparse transfer+training aware

---

src/sparsify/cli/opts.py
src/sparsify/cli/run.py

no reason to not allow custom use cases for one shot, for now, leaves warning that some features may be missing
**testing**
minimal reproducible example now passing:
```
sparsify.run one-shot --use-case some-custom-usecase --model mobilenet.onnx --data imagenet-val-sample-tiny/ --optim-level 0
```

[one shot] allow custom use cases with warning

---

src/sparsify/login.py

if python3-dev is not installed, sparsifyml will raise an import error over not finding the libpython binaries, this PR adds a bit more information to help the user out
**test plan:**
login pathway covered by GHA

Wrap sparsifyml import error with information about python3-dev requirement

---

src/sparsify/check_environment/ort_health.py

The recently added environment check cli was missing authenticated import of sparsifyml, 
This led to a `ModuleNotFoundError` instead of a `SparsifyLoginRequired`
Current PR fixes that.
Test Command:
```bash
sparsify.run sparse-transfer --use-case image-classification --data /network/datasets/imagenette-160 --optim-level 25
```
Command Output:
Before this PR: (Reported by @dsikka)
```bash
Traceback (most recent call last):
File "/home/dsikka/venvs/sparsify_main/bin/sparsify.run", line 5, in <module>
from sparsify.cli.run import main
File "/home/dsikka/sparsify/src/sparsify/cli/run.py", line 21, in <module>
from sparsify.check_environment import auto_checks, one_shot_checks
File "/home/dsikka/sparsify/src/sparsify/check_environment/__init__.py", line 19, in <module>
from .ort_health import …
```

Fix Sparsifyml not installed prompt

---

src/sparsify/auto/scripts/main.py

Tensorboard was outputting logs constantly when running a training aware command for a yolov5-n (base) model trained on coco, this made it difficult to see training progress or if training was actually being run or not. This PR fixes that by suppressing tensorboard logs
Changes include:
- Set the tensorboard logging level to warnings to suppress constant stream of tensorboard logs
Test Command:
```bash
sparsify.run training-aware --model "zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/base-none" --data VOC.yaml --use-case cv-detection --optim-level 0.5
```
Before this PR:
```bash
rahul at quad-mle-1 in ~/projects/sparsify (sparsify) 
$ sparsify.run training-aware --model "zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/base-none" --data VOC.yaml --use-case cv-detection …
```

Fix tensorboard reloading

---

src/sparsify/auto/tasks/object_detection/yolov5/runner.py
src/sparsify/auto/utils/helpers.py

- Provide the functionality to build a yolov5 yaml file, given the user provides an input directory to the `data` arg.  
- The following assumptions were made about the directory structure and a sample directory structure is shown below
- The directory passed in contains an `images` subdirectory, a `labels` subdirectory, and a file called `classes.txt` which contains the classes, ordered by class id
- Each of the `images` and `labels` subdirectories contains training, testing and validation folders
- The labels should already be in the format expected by yolov5
- yolov5 assumes the train, test and validation directories have identical names in both the `images` and `labels` folders
Sample Directory Structure:
```
- data_for_training/
- labels/
- train/
- val/
- test/
- images/
- train/
- …
```

Add functionality to build yolov5 yaml

---

docs/datasets-guide.md

the huggingface `datasets` library does not have support for a `.jsonl` extension. json lines format should still have `.json` extension

update requried json lines extension in datasets-guide.md

---

src/sparsify/cli/run.py

validation for the following rule:
`optim-level must be a float value between 0-1 or an integer value between 0-100`
scales any integer 0-100 to the float range so the run pathways can always expect the 0-1 range
**testing**
verified locally against variety of valid and invalid optim levels. also validated that optim-level 50 no longer breaks one-shot

[run] add validation for optim level

---

src/sparsify/auto/tasks/image_classification/runner.py

For this bug: https://app.asana.com/0/1204777926187571/1205045628929357/f
In the case where the user is providing a custom dataset, we want to check if the dataset directory exists.

[ImageClassification] Check if the folder exists for custom datasets

---

src/sparsify/auto/utils/helpers.py

For this ticket: https://app.asana.com/0/1204322589046915/1205045628929361/f
Previously we handled 2 cases:
- User provides path to a yaml
- User provides a directory of custom data + classes and we build the yaml for them
This adds the third case where the user provides a directory and we first check if a yaml already exists in the folder. If there is a yaml, we use that as the data.
Tested locally using a training-aware run

Update yolov5 yaml build to handle case where directory with yaml is provided

---

MANIFEST.in
src/sparsify/auto/tasks/deployment_instructions.md
src/sparsify/auto/tasks/object_detection/yolov5/runner.py
src/sparsify/auto/tasks/runner.py

- Add deployment instructions to the source code
- Add step to write the instructions to the `deployments` directory produced for the workflow and save the  file as `README.md`
Tested locally

Add deployment instructions to `README.md`

---

src/sparsify/auto/tasks/deployment_instructions.md

Update deployment instructions to install `deepsparse[server]`
Also added a link to download sample image
Note: this wasn't updated to deepsparse-nightly; as once 1.6 is recut deepsparse[server] would be enough

Update deployment instructions to install deepsparse[server]

---

src/sparsify/auto/tasks/image_classification/runner.py

- Default behaviour involves the user passing in just the `data` arg and this always results in `imagefolder` being populated in for the `dataset` arg, for both custom datasets and datasets where we download public data (this shouldn't be happening/should be separated further in a follow-up PR)
- However, we only want to check the existence of folders for custom datasets, not public datasets we haven't pulled down.
- Therefore, remove the check and error  
- This should also just be done in sparseml, since click.Path() is where the folder is created.
Tested locally using the following command:
`sparsify.run sparse-transfer --use-case image-classification --data imagenette --optim-level 0.5`

Move empty directory removal to sparseml instead of sparsify

---

setup.py
src/sparsify/auto/samples/finetune_llmfoundry_sample.yaml
src/sparsify/auto/tasks/finetune/finetune.py
src/sparsify/auto/tasks/finetune/helpers.py
src/sparsify/auto/tasks/transformers/__init__.py

Add helper functions to the `finetune` task which allows us to finetune previously sparsified models. This is done by attaching masks using buffers after the sparsified model is loaded, to any weight which has already been pruned. A Composer callback function is also added to apply the masks to the weights, after each step during training. These helper functions will be converted to be applied through a recipe in a follow-up PR.
llm-foundry has a requirement for `accelerate` which is incompatible with our transformers. Therefore, this moves `sparseml[transformers]` to the `nm` tag instead of making it a required installation. This allows us to install the correct `accelerate` for `llm-foundry` with the `llm` tag and the correct `accelerate` for `sparseml[transformers]` with the `nm` tag. …

LLM finetune sparsify masking

---

MANIFEST.in
setup.py
src/sparsify/auto/finetune.py
src/sparsify/auto/samples/finetune_llmfoundry_sample.yaml
src/sparsify/auto/scripts/main.py
src/sparsify/auto/tasks/finetune/__init__.py
src/sparsify/auto/tasks/finetune/args.py
src/sparsify/auto/tasks/finetune/finetune.py
src/sparsify/auto/tasks/finetune/helpers.py
src/sparsify/auto/tasks/finetune/runner.py
src/sparsify/auto/tasks/runner.py
src/sparsify/auto/tasks/transformers/__init__.py
src/sparsify/auto/utils/error_handler.py
src/sparsify/schemas/auto_api.py
src/sparsify/utils/constants.py

- Enable LLM finetuning in sparsify by adding support for the llmfoundry library
- This is done by adding an additional task called `finetune` which provides support for all the steps required for llmfoundry finetuning integration 
- Currently, this workflow launches finetuning given a llfoundry compliant yaml file (provided using the `--data` cli arg to the sparsify command)
- Exporting steps are currently skipped and as there is no sparseml support atm, in order to allow ddp training, `finetune.py` includes the steps which can be wrapped in `launch_ddp` and `trainhook`
- As the only essential arg is the `data` arg containing the yaml file, there are no `finetune` specific train args but this can be added in as greater finetuneing support is flushed out
- A sample yaml can be found under …

LLM Finetune Functionality

---

setup.py
src/sparsify/auto/tasks/transformers/__init__.py
src/sparsify/auto/tasks/transformers/llama.py

- Maybe this better belongs in `scripts` ? Uses the `TransformerExportArgs` schema
- Specific command for llama exporting which allows the user to export the model without having to go through any of the other auto pathways. Also sets majority of the exporting variables for them.
- Also clean-up imports for transformers tasks, fix typo in `setup.py` for for `nm` packages, and update the `finetune` command to be called `sparsify.llm_finetune` in `setup.py` (i.e. small changes for somewhat unrelated things which came up while putting up this PR) 
Tested locally using the newly added command: 
```
sparisfy.llama_export --model_path ./training/ --sequence_length 2048
```
This exports a model which successfully goes through KV Cache injection and is able to run in our pipeline (tested …

[LLAMA] Export Pathway + clean-up other imports/pathways

---

README.md

The link mentioned previously downloaded a wrongly generated dataset (it had fewer inputs); the new link and the dataset have been verified to work with the readme command locally
```bash
#!/usr/bin/env bash
export CUDA_VISIBLE_DEVICES=2
export SPARSEZOO_TEST_MODE="true"
export NM_BIND_THREADS_TO_CORES=1
export NM_DISABLE_ANALYTICS=1
sparsify.login XXXXXXXXX
sparsify.run one-shot --use-case text_classification --model "zoo:nlp/sentiment_analysis/bert-base/pytorch/huggingface/sst2/base-none" --data /home/rahul/datasets/sst2_bert_calibration --optim-level 0.5
```

[BugFix] Point readme to updated dataset

---

setup.py

Append date to major_minor_version only when building a nightly wheel
Tested by setting is_release to True
Also moves Neural Magic dependencies to _nm_deps as is the case for  our other repos

[Fix] Release Build trying to install dated versions of nm_deps

---

setup.py

Cherry pick for bug:
release build asking for dated versions of nm repos, for example asking for `sparsezoo~=1.6.0.202308` instead of `sparsezoo~=1.6.0`
This PR fixes that in 1.6 release

[Cherry pick] release version bugfix (#290)

---

setup.py

This PR removes reliance on dated nightlies from `setup.py`
```bash
$ pip list | grep nightly                                                                                                              (remove-dated-version-completely|…2)
deepsparse-nightly        1.7.0.20231207
nm-yolov5-nightly         1.7.0.20231206
sparseml-nightly          1.7.0.20231206
sparsezoo-nightly         1.7.0.20231206
sparsify-nightly          1.7.0.20231207       /home/rahul/projects/sparsify
```

[BugFix] Remove Dated Nightly
